### ISSUE TITLE
External Query not showing players online

### ISSUE THREAD

**Issue by megoesrawr** [NamelessMC/Nameless#12]
The external query is not showing the player heads of people who are online. No errors in query. (Internal query doesn't work with srv.)

**Comment by samerton** [comment]
This is actually intentional behaviour; the external query does not return a list of online players. This is out of my control as I have no way of hosting my own external query for Nameless unfortunately.

If you say you're experiencing issues with the internal query, can you head into your AdminCP's Minecraft tab, and select the Query Errors tab. There will be errors in there which can be used to fix your internal query; can you post them here?

**Comment by megoesrawr** [comment]
Failed to connect or create a socket: 0 (php_network_getaddresses: getaddrinfo failed: Name or service not known)

**Comment by megoesrawr** [comment]
I think the pre1.7 bit is backwards. When i had it on pre1.7 for my 1.8.8 spigot server is worked (without faces) on internal.

**Comment by samerton** [comment]
I'm going to change the way the domain/IP to be queried is set in an upcoming release; the domain displayed to users will be different to the domain queried, so you can input the IP address of the server directly (#16). Hopefully your issue will be resolved then.
