### ISSUE TITLE
Issue with admin cp

### ISSUE THREAD

**Issue by RSL2003** [NamelessMC/Nameless#1283]
* Bug
* Version:
2.5 if im not mistaken
* Description of issue: 
after around a week of my site being up the admin cp will end up being unable to be accessed.(with error 404) I've had to reinstall 4 times due to this issue 
* image of  issue:
https://imgur.com/1o3CViZ
* I am unsure how this issue occurs but i do know that the folder /admin is empty when this issue shows up. i can only think something is conflicting with it and ends up wiping the folder
* Modules enabled:
the only one that was enabled was the form module
* Themes enabled:
 i was using the dark theme

If there is no fix to this thats fine. if there is a file of the /admin folder that i could re upload for v2.5 that would save me a lot of time.
Thanks for your help 
Jared McRae Rogers

**Comment by samerton** [comment]
Hi,

There is no `/admin` folder included in Nameless. If you have an empty `/admin` folder, this may be conflicting with Nameless, giving the 404 error.

Hopefully, if this is the case, deleting the admin folder will fix the problem.

**Comment by samerton** [comment]
Were you able to take a look @RSL2003?

**Comment by RSL2003** [comment]
Yes I have @samerton.  It seems that is the problem but I am still unsure of what causes the issue. At least it saved another reset

**Comment by samerton** [comment]
Ah okay, glad the issue is resolved!

What was happening was:
- Nameless will redirect all traffic into the Nameless system if, only if the file or folder in the URL doesn't exist
- As the **admin** folder existed, Nameless did not direct the traffic into the Nameless system as the folder existed instead
- However, this folder was empty, so there was nothing to show to the browser, so the 404 screen was displayed
