### ISSUE TITLE
[Bug/Cosmetic] StaffCP Privacy/Terms Page

### ISSUE THREAD

**Issue by Tyrelis** [NamelessMC/Nameless#1307]
**Describe the issue**
When I press ctrl + a in the first text box, it sends me to the 2nd text box. The footer also does not display correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login into a admin privileged user and go to 'staffcp'
2. Click on 'Privacy & Terms'
3. Scroll down to the bottom of the page where you will see the 'footer'
4. You will see a css cosmetic issue within the footer.
5. Click on the first text box press and ctrl + a
6. You will notice that the selected box cursor goes to the second text box instead of the first.

**Expected behaviour**
When I press ctrl + a in the first text box, it should send me to the 1st text box instead of the second. As for the footer it should extend towards the left more as shown below in the pictures.

**Screenshots**
Bug: http://prntscr.com/ljzmds
Expected: http://prntscr.com/lk209h

**NamelessMC version (from AdminCP -> Overview)**
Namelessmc v2 pre-release version 5

**Additional information**
I made a proper bug report please close #1306 as a result thank you.
Credits to @baxandrei

**Comment by samerton** [comment]
Footer fixed in 0e704b83c0efa39b16686241af1c19be3e032983

As for the Ctrl+A issue, unfortunately I don't think there's anything that can be done about this. Everything I can see on the Nameless side is done correctly, I'm not sure if this is an issue within the editor library itself. I'll close this issue for now, in the future if I'm ever able to find out what's going on I can re-open and fix.

**Comment by baxandrei** [comment]
Ctrl+A it`s from editor library.
