### ISSUE TITLE
Editor doesn't work with some posts

### ISSUE THREAD

**Issue by ttaco** [NamelessMC/Nameless#1349]
Some posts I try to edit I cant see any text in the editor, And I get this error in the console:
Uncaught SyntaxError: missing ) after argument list

Steps to reproduce the behaviour:
1. Go to a post
2. Click on edit post
3. Open console

I was expecting that I could edit a post

I am using version 2.0.0-pr5

**Comment by samerton** [comment]
The issue occurs when there is an apostrophe `'` in the post.

This has been fixed in this commit, which will be included in the next release. It's possible to apply the commit now by editing the file **modules/Forum/pages/forum/edit.php** in a text editor, deleting all code inside and replacing with [this new code](https://raw.githubusercontent.com/NamelessMC/Nameless/a05e8e2eb64704dae2a9a158ea5c8e8fa9d44623/modules/Forum/pages/forum/edit.php).

**Comment by BrayaanPS** [comment]
I have the same problem but in 2.0.0-pr6 :/

**Comment by BrayaanPS** [comment]
I have the same problem with version 2.0.0-pr6, when I put the code in order to fix it, but with the old visualization
