### ISSUE TITLE
Font Awesome Issue and Rank Inheritances Hide

### ISSUE THREAD

**Issue by NPCtom** [NamelessMC/Nameless#1394]
How do you use the NavBar-Icon? I tried using tags from the Font Awesome cheat sheet but it came up as plain text. Could there be more documentation on that?

Also I have a user who is the rank 'Admin' I also manually selected he gets added permissions from the 'Member' rank. But in the forums it is shown he also has the Member rank. Can I hide this?

**Comment by samerton** [comment]
With Font Awesome in navbar icons, you'll need to use the full `<i class="....."></i>` tags. By default, the front end uses Font Awesome 4, so you'll need to use the v4.7 docs found [here](https://fontawesome.com/v4.7.0/) instead of the latest v5 docs.

With secondary groups, it's currently possible to either show all secondary groups in the forum or hide them all. If you want to hide them all, you can remove [these lines](https://github.com/NamelessMC/Nameless/blob/v2/custom/templates/Default/forum/view_topic.tpl#L92-L95) from custom/templates/*template*/forum/view_topic.tpl, and replace them with
```
{$user_groups[0]}
```
to simply display the first group (which will be the primary group).

**Comment by NPCtom** [comment]
When replacing those lines with ```
{$user_groups[0]}
```

It no longer displays any group.

**Comment by samerton** [comment]
Apologies, it should be `{$reply.user_groups[0]}`
