### ISSUE TITLE
Server Status Not Working V2.0

### ISSUE THREAD

**Issue by NPCtom** [NamelessMC/Nameless#1399]
We have a BungeeCord server and the server status is displaying as 'Offline'.

How do we fix this issue?

**Comment by samerton** [comment]
Firstly, make sure the "External Query" option is disabled in the StaffCP -> Integrations -> Minecraft -> Servers tab, as the external query service used by pre-release 5 has been shut down (this has already been changed for the next update).

If you're getting the issues with the external query option disabled, check the StaffCP -> Integrations -> Minecraft -> Query Errors tab to see what the problem is.

**Comment by NPCtom** [comment]
I am very confused.

We have a BungeeCord server.

We have a domain play.kraken-network.net that redirects to our server by using DNS records.
What do I put in the server port and query port?

**Comment by samerton** [comment]
I don't actually believe these are used for anything yet, but if you want to enter something it'd usually just be `play.kraken-network.net` with port 25565.

**Comment by samerton** [comment]
Were you able to check the StaffCP -> Integrations -> Minecraft -> Query Errors tab to see if there's anything in there?

**Comment by NPCtom** [comment]
Failed to connect or create a socket: 111 (Connection refused)

**Comment by samerton** [comment]
Okay, this is one to contact your web host about. Either:
- they do not allow the use of PHP sockets, or
- their firewall is blocking port 25565 (or whichever port your Minecraft server runs on)

**Comment by samerton** [comment]
Were you able to resolve the issue @NPCtom?

**Comment by NPCtom** [comment]
@samerton No I was not, still awaiting a reply from hosting provider :)
