### ISSUE TITLE
Enlarging the Header Image on Front Page

### ISSUE THREAD

**Issue by ryancito02** [NamelessMC/Nameless#140]
Hello again, I have recently began delving headfirst into your code ever since I found out what you licensed it under. I have been trying to make the Image Header on the front page of the website expand from left to right, and also make contact with the top. However, I have googled the commands to do this, by changing the     /var/www/pages/index.php   in the Jumbotron section.

Here is my index.php - 
[index.txt](https://github.com/NamelessMC/Nameless/files/183381/index.txt)

( Had to copy and make it a .txt for drag and dropping)

Now you see the lines I have edited, under .jumbotron.

Now, according to a PHP website, 0% and 0% places the image in the upper most left corner, but in my case, nothing happened.

That's right, nothing. The image remained in the middle with the whiteness surrounding it..

( And Yes, I did restart my Apache2 Server)

Any help, o omnipotent Samerton?

**Comment by samerton** [comment]
You'll probably have more luck editing the template file (styles/templates/*Your Template*/index.tpl) than the css directly.
I've changed the template as a test, you can find the code [here](https://gist.githubusercontent.com/samerton/16dbb6755808ac4bd4fe/raw/bfb04956d45a1836113e08cedc76a7fea182a727/index.tpl) (apologies about the line indentation, it seems to have messed up a bit after being pasted).

What I've done is moved the jumbotron element out of the `<div class="container">` and removed the line breaks, and then in order to get the text within the jumbotron to display nicely I've then put a container within the jumbotron itself.

Hope that helps.

**Comment by ryancito02** [comment]
I'm sorry, could you maybe provide more information or instructions on how to do this?

I have not messed with the Templates section of the website as of yet, and only use the Default ones.

Could you include some instructions on how I may create my own template file, arrange for it to stretch the image to the top (below the menu bar) and to the sides?

Thanks!

**Comment by samerton** [comment]
@ryancito02 

You can duplicate the existing template folder (styles/templates/Default), and name your theme anything you wish. Next, paste the code in my previous reply into the "index.tpl" file within your newly created template.
Finally, head into the AdminCP -> Style -> Templates tab, and click the "Install Template" button, and then "Scan". You can then activate your newly created template.
