### ISSUE TITLE
Email Issues

### ISSUE THREAD

**Issue by JavaGuy12** [NamelessMC/Nameless#1541]
### Template:
* What kind of issue is it (Question, Bug, etc.)?
Question
* In which version of NamelessMC did it occur (1.x.x)?
2.0.0-pre6
* How would you describe the issue?
Issues using both PHP mail() and SMTP email functions
* Do you have (relevant) resources about this issue (Logs, pictures, etc.)?
n/a
* Do you have an idea how or where the issue occurs?
The issue occurs while attempting to send a test email in the StaffCP.

---

Hello. I recently set up NamelessMC 2.0-pre6, and opted for a host where I had cpanel. I've used Nameless before with NamelessHosting.com, however I wanted full control this time. The email function is acting up. I set it to use mail() (which theoretically should work, as I checked my host's polices and it says that they support PHP mail() for Cpanel created emails (which mine is). This threw no errors, but didn't send the emails. I then tried enabling SMTP (which they also support), modifing the /core/email.php file to hold the correct port (465). All of the info is correct, but it throws a SMTP connect() failed. I looked through the troubleshooting and all of it was irrelevant to my situation. Thanks in advance!

**Comment by samerton** [comment]
When using the built-in `mail()` function, have you checked your junk/spam folders? If so, it's worth contacting your host if you want to use it.

With SMTP, in order to get full debug information, try the following:
- Edit **core/classes/Email.php** in a text editor
- Delete all code inside and replace with [this new code](https://gist.githubusercontent.com/samerton/a26df55561f9735eb2f69af6868f57fb/raw/5f5581c6faa44c596eebccaa32d6c0efa8f79a81/Email.php)
- Send a test email to get a full debug log on screen with further information

Once you have your debug log, it's best to reset **core/classes/Email.php** back to its [original code](https://raw.githubusercontent.com/NamelessMC/Nameless/v2/core/classes/Email.php).

**Comment by JavaGuy12** [comment]
Thanks so much for your quick reply. I’ll be doing that as soon as possible.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JavaGuy12** [comment]
```
x10host.com:465, timeout=300, options=array ()
Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): unable to connect to ssl://royalcla.x10host.com:465 (Connection refused)
SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```
The above is the extra info that it returned. the domain and port are correct; I've checked. A refused connection means I need to edit something in CPanel, maybe? Thanks again for the help.

**Comment by samerton** [comment]
This might be one to contact your web host about; the email server host/port combination seems incorrect as it's not returning anything.

**Comment by JavaGuy12** [comment]
Alright. I'll contact them, and I'll (hopefully) reply to the thread with any info that others could use.

**Comment by samerton** [comment]
Any luck with this @JavaGuy12?

**Comment by JavaGuy12** [comment]
Nothing back... they’ve got a support forum and I haven’t gotten any replies yet. Sorry.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by samerton** [comment]
Going to mark this as closed as I think this is server configuration/SMTP details related. If you are still having issues please feel free to re-open 👍
