### ISSUE TITLE
While querying a BungeeCord Proxy, it does not count any players

### ISSUE THREAD

**Issue by ThemInspectors** [NamelessMC/Nameless#157]
If you set your BungeeCord Proxy as your main server it does not count any players in could you add an option to on the main server inherit from S1, S2, S3 ect.?

**Comment by samerton** [comment]
The Bungee query will return the number of players, however due to restrictions it can't return a list of player names. 
In order to have a player list of everyone across all servers, you need to define each backend Spigot instance separately, but keep the main server as your Bungee instance. As a result, you'll get something like this on the Play page: http://i.imgur.com/shwnWmz.jpg

**Comment by ThemInspectors** [comment]
So will the Inherit option be available?

**Comment by samerton** [comment]
Not in the foreseeable future, as it'd lead to performance issues (every server inherited would need querying, which would slow the site down considerably, by at least a few seconds).

**Comment by samerton** [comment]
Just to add onto the previous post, I'm hoping to improve support for multiple servers in 2.0, so hopefully I can do something similar there.

**Comment by ThemInspectors** [comment]
Any queryed server would be shown as its own & then the server who inherits it reads the already placed data

**Comment by samerton** [comment]
Inheritance added in the upcoming v2 release
