### ISSUE TITLE
I Change an option in the cp staff and now my website dont change

### ISSUE THREAD

**Issue by Prowco** [NamelessMC/Nameless#1574]
**Describe the issue**
Hi  i change a option in the server options i think its the option https secure or something like that, and now my website dont open at all so i cant change this in the panel bc my website dont open where i can change it in the files?

**To Reproduce**
[MineCityRP](http://www.mcrp.ml/l)
You can see here my website dont work since i change that option

**Additional information**
I use the template Minebox

**Comment by Derkades** [comment]
In order to force HTTPS on your v2 website you have to have a valid SSL certificate.
To check if your SSL certificate is valid you can go to https://yoursite.com and check if it says "Secure Connection" when clicking on the lock in the url bar.

Force HTTPS does not work with Cloudflare "Flexible" SSL, if you do not have a valid SSL certificate on your web host or a vps, then you can force HTTPS with Cloudflare "Flexible" SSL in Cloudflare "Crypto" section.
If you do have Cloudflare SSL set to "Flexible" and you have a valid SSL certificate on your web host or a vps, then you have to set your Cloudflare SSL to "Full" in order to use force HTTPS function in NamelessMC.

If you get an error after enabling force HTTPS you can disable it by deleting cache/033f3da34ae9ec9661072ab0897ddf7ed642de3f.cache file.
