### ISSUE TITLE
Virtual Hosts are not working correctly

### ISSUE THREAD

**Issue by Samistine** [NamelessMC/Nameless#16]
Bungeecord's Forced Hosts allow pinging to different backend servers depending on the hostname you are using to connect eg creative.exampl.com survival.exampl.com

**Comment by samerton** [comment]
NamelessMC uses an external library to query servers ([found here](https://github.com/xPaw/PHP-Minecraft-Query)). I'm not entirely sure how the forced hosts work; I've added a resolver to the query to determine where a domain is pointing, however if there's still no luck it may be worth creating an issue over in the [query's issue tracker](https://github.com/xPaw/PHP-Minecraft-Query/issues).

**Comment by Samistine** [comment]
It's similiar to Apache's virtual hosts, or any shared hosting platform for that matter. Depending on what hostname is used in the connection/query it determines which server to forward you to. Since your querying with the IP instead of the domain, it won't work correctly.

**Comment by Samistine** [comment]
Yep, library works perfectly. You just have to query the domain instead.

**Comment by samerton** [comment]
In order to allow the query to work with SRV records, I've had to resolve domains to their IP.
If I understand you correctly, the forced hosts won't work with this method, so I'll create a new field within the AdminCP's Minecraft tab to allow users to specify the domain they want to query, alongside the domain they want to show.
I can then drop the SRV resolver, so that whatever the user inputs in the new field (whether it's the IP the SRV record resolves to, or the domain name for forced hosts) is queried.
