### ISSUE TITLE
issues :(

### ISSUE THREAD

**Issue by thebeastgamer25** [NamelessMC/Nameless#169]
**1**. I cant access any other page in the admin cp other than overview :(
**2**. The email is not working :(

questions : 

how do i make other people admin?

**Comment by thebeastgamer25** [comment]
oh and btw, samerton, if u can plz help!

**Comment by samerton** [comment]
What happens when you try to access other pages in the AdminCP?

You can make other users admin by editing them in the AdminCP's "Users and Groups" tab. If you want to make a custom admin group, you can do so in the AdminCP -> Users and Groups -> Groups tab by creating a new group, editing it and then checking the "Can the group view the AdminCP?" option.

As for the emails, there are a few options available.

The first is to install sendmail (**sudo apt-get install sendmail** and then **sudo sendmailconfig**), and then configure PHP to use this (see the "Configuring PHP mail() function" section of [this page](http://developernote.com/2012/07/how-i-configured-sendmail-for-php-on-ubuntu-server-12-04/)). 

The second is to configure Nameless to use either an SMTP server or Gmail. If you want to use SMTP, try the steps in [this post](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-67#post-1017639), and if you want to use Gmail try [these steps](https://www.spigotmc.org/threads/nameless-minecraft-website-software.34810/page-70#post-1036444) instead. After completing either of these, you need to head into the AdminCP -> Core -> Email and disable the "Use PHP mail() function?".

Finally, you can disable email verification altogether by disabling "Enable email account verification?" in the AdminCP -> Core -> Email tab, although this isn't recommended as it could effectively mean users can register with any email address.

**Comment by thebeastgamer25** [comment]
when i try to, it bumps me back to the overview page

**Comment by thebeastgamer25** [comment]
btw, the link is emeraldcraft.x10.mx

**Comment by thebeastgamer25** [comment]
hello? samerton?

**Comment by samerton** [comment]
I've not seen your issue with the admin panel before, I'd have to take a look to see if I can find a possible cause.

**Comment by thebeastgamer25** [comment]
plz do!

**Comment by ImACorndog** [comment]
Hey man, I was having the same issues with only being able to look at overview and I think I found the problem. It's the hosting company you're using. I was using the same one as you then I switched over to byet hosting and it's working for me now.

**Comment by samerton** [comment]
Thanks @ImACorndog, as you say it must be a host issue.

I'm going to close this for now as I don't believe it's a problem with Nameless.
