### ISSUE TITLE
Custom Pages do not save html source codes properly on second submit.

### ISSUE THREAD

**Issue by HeavenCrafter** [NamelessMC/Nameless#1723]
**Describe the issue**
I have a custom page that is called "Our Partners" and most of the UIs and stuff are completely custom coded and pasted into the edit sources. The problem occurs when you submit the page on a second time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a custom page, paste in any sort of HTML or in my case, semantic source code.
2. Click on submit.
3. Go back to the custom page
4. Submit again without any changes.

**Expected behaviour** - What it should look like and should STAY look like.
![image](https://user-images.githubusercontent.com/22242534/86396145-fa332a80-bcd3-11ea-9008-a99b4176e797.png)

**Behavior that I got instead** - Only occurs whenever you submit the page for the second time but without any changes to the code.
![image](https://user-images.githubusercontent.com/22242534/86396063-dbcd2f00-bcd3-11ea-8935-7134aedd6cf4.png)

**NamelessMC version (from AdminCP -> Overview)**
Latest, v2.0pre7

**Additional Information**
The only way around this is to paste the proper code in each time before pressing onto submit.

**Comment by Aberdeener** [comment]
Interesting, I'll try to recreate this

**Comment by HeavenCrafter** [comment]
If you need me to send the code I used, hit me up on Discord! Heaven#2944

**Comment by nimbus321** [comment]
I think this is because the editor shows you the html code already previsualized and it's not actually identical from the original code, so when you upload it "again", it actually uploads the modified version that was converted to show the preview.
 You can see what I mean by uploading the code for the first time, and later go to the editor page and click the html option, you will see it's actually a bit different. I'm no expert but I think maybe this is why?

**Comment by Aberdeener** [comment]
I believe this has been fixed with the removal of CKEditor.
I tested some "complex" HTML in custom pages, and everything seemed fine after editing it many times.

If this issue comes up, please re-open this and attach the HTML you are having the problem with
