### ISSUE TITLE
Slow loading time - Users StaffCP

### ISSUE THREAD

**Issue by Leyji** [NamelessMC/Nameless#1752]
**Description**
When I try to display registered users (large amount of users - 7000+) in staffcp, it takes way too much time to load. I can't even search (not a connection issue)

Steps to reproduce the behaviour:
1. Go to /panel
2. Click on users
3. Wait till the users load

**Expected behaviour**
Load users instantly.

**Screenshots**
None

**NamelessMC version (from AdminCP -> Overview)**
2.0.0-pr7

**Additional information**
None

**Comment by Aberdeener** [comment]
Hey!

~7000 is not a massive number in the context of MySQL queries, so I wouldn't expect this page to take longer than 3-5 seconds on a decent dedicated machine. 

The best thing I can tell you is to host the MySQL server on the same machine as your web server - so that there is no network latency.

Aside from that, unfortunately, there is no easy way to fix this or speed it up.

As you can see [here](https://github.com/NamelessMC/Nameless/blob/db173d370ec3bfa2938927368a972cb29ac8160f/modules/Core/pages/panel/users.php#L60), right now we just grab all the users from the `nl2_users` database and perform a few lightweight tasks on them. 

We can definitely look at a better way to "paginate" bigger queries (such as this).

Sorry about that, I'll try to keep you updated and maybe @samerton has some alternative thoughts or solutions about this?

**Comment by partydragen** [comment]
@Aberdeener Its a knowed issue

On my site i have 7000 too and it taking 45000 mysql queries
table take alot of time too

problem with paginaten is that don't have live seaching and boostrap don't have a good live searching from what i know

**Comment by IsS127** [comment]
I have noticed this issue aswell, if I remember correctly this goes back to v1.

**Comment by Aberdeener** [comment]
Samerton just changed the user list to be ajax, which significantly boosts the speed of the page. When pre8 releases, feel free to reopen this issue if you find it is still very slow.
