### ISSUE TITLE
Update Failing??

### ISSUE THREAD

**Issue by FunkiestPeak** [NamelessMC/Nameless#187]
Whenever I try to update my current site, it doesn't seem to load correctly. I do as it says on the site, I'll download the update, copy and paste the files. But when I paste the files it just replaces duplicates and the site loads the installation page for a new site?

**Comment by samerton** [comment]
The update packages don't include the install file (as long as you download it from the AdminCP's Update tab, and not from Github), if you're always getting this problem manually delete **pages/install.php** and then see if you can run the upgrade script (also in the AdminCP's Update tab).

**Comment by FunkiestPeak** [comment]
Ok then I believe I got it from GitHub.

**Comment by FunkiestPeak** [comment]
I got the download through the panel and it gave me this error -

" 'MY IP ADRESS' is currently unable to handle this request."

My Ip address is the my computers public ip as I am running it locally.

**Comment by samerton** [comment]
Can you check your Apache error logs for the most recent errors? The location will differ depending on your setup, however on XAMPP it's usually **path/to/xampp/apache/logs/error.log**

**Comment by FunkiestPeak** [comment]
I am very new to this so I have no clue what any of this means my good sir but, here is the log if you'd like to take a look.
[apache_error.log.zip](https://github.com/NamelessMC/Nameless/files/258340/apache_error.log.zip)

**Comment by samerton** [comment]
There don't seem to be any PHP errors in there, which is what we'd need to diagnose the issue.

The easiest thing to do here would be to reinstall using the same database, so no data would be lost.
If you download the version you were running **before** attempting to upgrade, and remove and replace all web files, you can then edit **core/config.php**, paste in [this code](https://gist.githubusercontent.com/samerton/d1c41dd9f7b4778ea65cb2afba354362/raw/225eb318bb743f184ed0b738a98fd92b42fbacb0/config.php) and fill in your database details.

Hopefully your site will be running again, and then you can upgrade, but always make sure you download updates through the AdminCP instead of GitHub.

**Comment by samerton** [comment]
Were you able to resolve this issue?

**Comment by samerton** [comment]
I'm going to close this issue, if reinstalling (whilst keeping the database) doesn't work feel free to reopen this.
