### ISSUE TITLE
Merge EnglishUS and EnglishUK

### ISSUE THREAD

**Issue by CqldFire** [NamelessMC/Nameless#1914]
I suggest that either EnglishUS or EnglishUK language be removed, and the other renamed to simply English. There is no reason to have both because UK and US English are practically the same anyways.

**Comment by BaxAndrei** [comment]
I agree with this ideea.

**Comment by samerton** [comment]
Originally there was just the 1 English language, which is now English UK, but people didn't seem to know about the difference between UK/US English.

I received multiple messages informing me of "spelling mistakes" and people even offered to become the main English translator because of these "mistakes".

Because having these separate language options makes it clearer to people, personally I'd prefer to keep them. As a Brit, if I was to remove one it'd be US which would bring the confusion back.
