### ISSUE TITLE
Collapsible options don't show on mobile

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#2347]
I have a problem when I click on dropdown things, it doesn't show anything. Sometimes it works but not now. Tested on V2-pre9 and V2-pre10.

https://user-images.githubusercontent.com/71085027/126874061-e8dfb544-63b4-4fa5-b902-604fe24c07d6.mp4

https://user-images.githubusercontent.com/71085027/126874078-e908ce56-0d91-432c-aae7-03875a61cc6f.mp4

**Comment by PadowYT2** [comment]
The same thing with V2 Pre11

**Comment by PadowYT2** [comment]
heres when if it fixed (pc)
https://cdn.discordapp.com/attachments/765928327113867295/889437689600946186/unknown.png

**Comment by Aberdeener** [comment]
I dug into this today, and found the issue.
https://github.com/NamelessMC/Nameless/blob/86c638ec6b4ac3756b8e6124bf6c5e3e5e946640/custom/panel_templates/Default/assets/css/custom.css#L314-L318

These lines in `custom.css` make it so that when the bar is collapsed (thin mode), it has a scroll bar - but this prevents it from popping out to the right when you click on a collapsible menu.

I removed these lines, and the collapsible menu worked again on mobile, but the bar was not scrollable - so 1/4 of the buttons were off the screen and impossible to get to...

Not totally sure how to resolve this, but at least we know the problem

**Comment by PadowYT2** [comment]
Solution: If sidebar items longer than device screen, make footer at the bottom, so that u will need to scroll the page like original sb admin 2 does
