### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by russianpeanut** [NamelessMC/Nameless#2372]
**Describe the issue**
so the language of my website is Czech, and some czech text looks like this "ðŸŽ‰ OtevÅ™ení SoupPvP"

**To Reproduce**
its almost everywhere

**Expected behaviour**
to it to be normal

**Screenshots**

**NamelessMC version (from StaffCP -> Overview)**
2.0.0-pr10

**Additional information**

**Comment by samerton** [comment]
Hi,

Which page is this on? Is it in a forum post for example?

**Comment by russianpeanut** [comment]
its almost on every page, homepage, forum page, forms, "more" at navbar etc... https://www.diamondlands.net/

**Comment by partydragen** [comment]
Hi, 

This is caused by after you upgraded to Pr10 with is force setting charset but as the damage has already been done you may revert the change by changeing the /core/classes/DB.php to https://github.com/NamelessMC/Nameless/blob/5b5acecbcc60379122c999ad9c5afff0bbeaf00d/core/classes/DB.php

BUT, Reverting can also cause damage as all groups/forums well everything that you have submited to update after pr10 will be lost if you revert the text will completly disappearer
