### ISSUE TITLE
API Endpoint for just updating the user's nickname

### ISSUE THREAD

**Issue by ByteExceptionM** [NamelessMC/Nameless#2569]
### Describe the feature

As requested, the issue for remembering @Aberdeener to add this endpoint. 

With this endpoint, you should only be able to update the nickname of a forum user without updating the username.

**Comment by samerton** [comment]
We'll be moving our APIs over to a more RESTful standard in the near future (hopefully pre-release 13)

The way this should work is, a partial PUT request would be sent to the `/user/{id}` endpoint, with a body as follows
```json
{
  "nickname": "new nickname"
}
```
so instead of having an endpoint specifically for updating nicknames, the user endpoint will accept any combination of fields to be updated.

I've just created a REST API issue here: https://github.com/NamelessMC/Nameless/issues/2572 so I'll close this in favour of the new one
