### ISSUE TITLE
Minecraft->web group sync does not trigger web->discord sync

### ISSUE THREAD

**Issue by MakeItReaal** [NamelessMC/Nameless#2581]
Dear Namelessmc-Support,

https://github.com/NamelessMC/Nameless/issues/2036

I got the same problem currently got the latest version of NamelessMC plugin from spigot and everything setup.
Currently ingame sync and website works perfectly fine. But when i add or remove a rank it wont sync on discord anymore. And when i delete the plugin discord and website syncs again.
do you know a solution for this? I'm able to screenshare if needed.
Also the API Endpoint is updated got all the routes needed.

Also there are no error in console or on the website. 

Kind regards.

**Comment by Aberdeener** [comment]
This has been fixed since pr12, you can attempt to add this commit yourself: https://github.com/NamelessMC/Nameless/commit/e221826eaf6a31619fe87ef590b2b911b9f198c4

The entire group sync system has been rewritten for the next update, which should hopefully clear up all these issues.

Feel free to reopen if that fix does not work, can try my best to help, but cant do much since the system is totally different now. Thanks!
