### ISSUE TITLE
Favicon and some suggestions.. [Favicon Solved]

### ISSUE THREAD

**Issue by IsS127** [NamelessMC/Nameless#280]
Hey can you add a favicon option in the admincp i need it rn.. if not is there a way to do it in .htaccess.. doesnt work for me when i set this:  
 RewriteRule ^favicon.ico  /var/www/vhosts/ispiracraft.com/httpdocs/favicon.ico [L]
im not sure if it goes and checks from root the httpdocs is the default public_html place.. ty.

And now for my suggestions.
Add a little button like the rank in the user page if the user is banned or tempbanned beside the Rank and the button should redrict to the infractions ban id(Button is not able to click but the text is)
fix so if there isnt any ban id it should bring the 404 error page.
Fix the follow message(ive changed it)
alert when someone adds u as friend or follows u.
an Option on topic only for mod+ so they can alert every user with a message to view the topic.
this might be hard u can add this in the future i dont really need it rn i can code a bit myself, a Page builder! drag and drop and that like the one invision board uses or make you're own custom!
make the server status show statics and show how many players joined today, this week, this month, like enjin.com does!
_OPTIONAL_ add support for this plugin http://dev.bukkit.org/bukkit-plugins/jpanel/ (it connects to server so im guessing when the nameless plugin is out u can do this?) or just make a custom console.

 well thats all i have cya! and goodluck keep up the great work.

**Comment by samerton** [comment]
Hi,

You'll need to upload your favicon to the **core/assets** folder in order for Nameless to load it.

As for the suggestions:
- Infractions on profile page: I'm planning on integrating infractions with profile pages in the near future
- Follow message: Hoping to get this fixed today
- Follower/friend alerts: Sure, this can also be added
- Alert on moderator post: Instead of a global alert, the upcoming announcements system (#213) can be used for this
- Page builder: The current template system is probably the only layout customisation that will be possible, drag and drop editors are unlikely unfortunately
- Stats: This is a possibility for the future, unfortunately I'm no Java developer so I don't know when this could be done by
- Built-in panel: Again, this is a possibility for the future, I probably wouldn't use an existing plugin like that, but rather develop a new one.

Thanks for the suggestions :)

**Comment by IsS127** [comment]
oh and another suggestion, to add a favicon option in the panel xD plus it didnt work.. is there any code i need to put in the .htaccess??

**Comment by samerton** [comment]
I could add an option to upload a favicon, however a manual upload is probably how it will stay for the time being.

It should work fine by default, could I have a link to your site?

**Comment by IsS127** [comment]
http://ispiracraft.com/ and could it be beacuse its a .ico file?

**Comment by samerton** [comment]
The favicon seems to load okay for me, can you try forcing a refresh in your browser (ctrl-F5)?

**Comment by IsS127** [comment]
it works? tried doing that many times before, gonna try to do it throught settings

**Comment by IsS127** [comment]
wait what image is it? is it this 
![server-icon](https://cloud.githubusercontent.com/assets/8834158/16424199/734eefa6-3d5f-11e6-9348-837ac9c0162c.png)

**Comment by samerton** [comment]
Yup, that's the image:
http://i.imgur.com/Zso1c1W.png

**Comment by IsS127** [comment]
ty for checking, for some reason it wont update for me!
