### ISSUE TITLE
Use transactions for v1 upgrade script

### ISSUE THREAD

**Issue by samerton** [NamelessMC/Nameless#2812]
### Describe the feature

Use MySQL transactions for v1 upgrade script instead of ignoring foreign keys

**Comment by Aberdeener** [comment]
This can be done by using the `DB::getInstance()->getPdo()->beginTransaction()` method, however this would be annoying to repeat in many places.
I'll create a new method on the DB class to execute a closure within a MySQL transaction to remove some of the boilerplate - then leave it to you to implement this since I'm not too familiar with the upgrade portion of Nameless.

**Comment by Derkades** [comment]
Do note that (in MySQL/MariaDB) operations like creating a table don't work with transactions, they are immediately committed. So, you must take care to only wrap the specific INSERT queries in the nice new transaction() function

**Comment by samerton** [comment]
Not going to follow through with this one, we're not gaining anything switching over to transactions since what we already have is functionally equivalent (doesn't stop the whole upgrade if we get a failure etc) - minimal gain considering how few people will be using it!
