### ISSUE TITLE
MariaDB version is reported as "MariaDB"

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless#2834]
![image](https://user-images.githubusercontent.com/15892014/172215645-fc76e172-02b3-412c-9b15-55ac8450f40c.png)

**Comment by Aberdeener** [comment]
Hmm, this is due to using the offset of `1` instead of `0` here:
https://github.com/NamelessMC/Nameless/blob/1e007bebe87b4a0aa20216b150b9e9b72add4ac0/modules/Core/pages/panel/index.php#L171-L174

Maybe the Stackoverflow article I read for reference is outdated now.
@Derkades Does NamedHosting use MariaDB so I can test a fix?
