### ISSUE TITLE
Plugin ban sync does not unban

### ISSUE THREAD

**Issue by Aberdeener** [NamelessMC/Nameless#2935]
https://discord.com/channels/246705793066467328/247865182477484032/999481725690314782

**Comment by partydragen** [comment]
And it does not register it to punishments making it impossible to revoke the ban, Also it should respect the groups so staff users can't be banned same as punishments page behavior

**Comment by supercrafter100** [comment]
I'm guessing that an unban endpoint has to be implemented for this to function at all

**Comment by Derkades** [comment]
Also the "not registering to punishments" issue sounds like an issue with the namelessmc ban endpoint?

**Comment by Derkades** [comment]
In any case, this is intended behavior. The option is described as:

>  When a player is banned, also ban their website account if they have one.

When a player is banned, it simply checks for a namelessmc account linked to their username and bans that as well. It does not sync existing bans before the option is enabled, and it does not do anything with unbans, because there is no way of unbanning Nameless accounts using the API.
