### ISSUE TITLE
Extend report API with field for Minecraft server id

### ISSUE THREAD

**Issue by b0hle** [NamelessMC/Nameless#3190]
### Describe the feature

With the implementation of the NamelessMC plugins in-game, using /report has become really useful for universal reporting across websites and in-game. I would love to see the ability to see the server where reports are coming from. This is really useful information.

**Comment by tadhgboyle** [comment]
Hey there 👋🏼 

You are already able to see where reports originated from on the user reports list page (see the "Origin" column):
<img width="1717" alt="Screenshot 2023-01-14 at 23 33 38" src="https://user-images.githubusercontent.com/26070412/212528578-938103a2-394a-41df-b8ed-5d05b00114ab.png">
If the report came from the plugin, this would display "API" instead of "Website".

That said, there is no way to see the report origin from the report page itself yet!
Does this way of displaying seem reasonable to you?
<img width="1725" alt="Screenshot 2023-01-14 at 23 34 14" src="https://user-images.githubusercontent.com/26070412/212528600-51ddd7d0-1d49-4786-b77f-93b03e298755.png">

Thanks for the suggestion

**Comment by b0hle** [comment]
I am sorry I didn't really specify very much. I want to be able to see what servers the reports are coming from the in-game plugin. As of right now, it just displays API when a report is submitted in game.
