### ISSUE TITLE
Website is available when installation is not finished

### ISSUE THREAD

**Issue by PadowYT2** [NamelessMC/Nameless#3294]
### Describe the issue

You could not finish the install but still visit the website kinda broken

### NamelessMC Version

Development version

### Expected Behaviour

It should redirect to /install.php

### Additional Information

We should fix it for 2.1!

**Comment by supercrafter100** [comment]
It happens because core/config.php is made past that step, thus no redirect is issued. Perhaps re-adding the installed property inside the config which only gets put when the installation finishes is a possible solution? Then we can check if the config exists and if that installed property is set to true, if its not then the installation hasn't finished
