### ISSUE TITLE
[Suggestion] Using a router and template library and less bootstrappy design

### ISSUE THREAD

**Issue by rodymol123** [NamelessMC/Nameless#388]
**What kind of issue is it (Question, Bug, etc.)?** Suggestion.

After setting up and working with NamelessMC for a few days I'd like to make a few suggestions for a future update (perhaps a 2.0?).

First and foremost; For an application like NamelessMC it might come in handy to embrace the routing and controller method of development. It could make it easier for others to contribute to the project and would make the project more maintainable in the long run. 

Second; After seeing the templates of both the frontend and the backend (admin) I'd like to propose using a templating library like Twig. It would allow for securely displaying data as a default and will make it easier to create templates for both the admin and frontend.

And last; I'd like to propose (or even work on) an all Nameless design for the admin panel. The UI currently isn't very consistent and makes it difficult to easily browse all different settings at a glance. Seperating the admin design and the website itself would also seem like a good practice.

I'm available for any design or JavaScript work if you'd like. I usually keep the basics of bootstrap for easy development and then add custom components to it, and strip away components that aren't necessary. This would include some buildtools in the project e.g. (gulp)

**Comment by Cl1608Ho** [comment]
I chose nameless exactly because it is pretty simple and straightforward and because it is built with bootstrap. At the moment, I am running something like a local fork of it and I use the forum and made a few changes. Things like exposing the latest news (threads in a forum) as Api so I could embed it in the homepage; or replacing the index.php with a redirect to /forum. Additionally I managed to get the design of the forum almost exactly the same as the design of the homepage. 

I would rather not use such systems, although I never got to use them. Maybe still keep a bootstrap design.

**Comment by samerton** [comment]
Thanks for the suggestions.

The current 1.x release is a bit of a half-and-half system in terms of templating. 
All requests are routed through the main index.php file, which determines which file to load based on the URL. It then finds the correct file in the **pages** directory, some of which do use templates from the **styles/templates** directory (using Smarty, I personally prefer this to Twig).

Version 2.0 which I've been developing slowly since the start of the year improves on this a lot, and allows for addons to become more powerful. Instead of searching through the **pages** directory for the corresponding file, addons can define which files should be loaded from different URLs.

The AdminCP in version 2.0 is also totally separate from the main site, this was done as version 2.0's theming system allows for non-Bootstrap themes, and also to maintain a consistent AdminCP appearance. Admittedly I'm not one for interface design, I'd really appreciate any help with that :)

**Comment by rodymol123** [comment]
If you'd like to see some examples of my interface design work (with focus on responsiveness), just hit me up at rodymol123 on Skype or Twitter :P

**Comment by samerton** [comment]
Should have been improved in the first v2 pre-release ([repo](https://github.com/NamelessMC/Nameless/tree/v2))
