### ISSUE TITLE
Images Border and Size not working

### ISSUE THREAD

**Issue by HappyHarm** [NamelessMC/Nameless#42]
Hi there,

As the title says when I change the border and size of an image it does nothing.

Btw do you accept donations or something by PayPal? Think it would be fair to do a small donation for all your help :P

**Comment by samerton** [comment]
Could you paste the exact HTML you're using for the image? It'll be a case of the attributes not being allowed, I can add them now though.

**Comment by HappyHarm** [comment]
It are attributes that you can add when you click on the image icon. Will paste them in a minute.

**Comment by HappyHarm** [comment]
<p><img alt="" src="http://gravelcraft.nl/images/ideal.png" style="border-style:solid; border-width:2px; height:65px; width:200px" />

**Comment by samerton** [comment]
Fixed in the latest commit.

Generally, to apply the changes in a commit you'll just need to replace the code manually, however some changes require database changes and it's probably best to wait until the next version is released, when there will be an upgrader included.

As for PayPal, I don't have a donation button set up yet but I may add one in the future.
