### ISSUE TITLE
Add ability to change the number of latest posts

### ISSUE THREAD

**Issue by zikycz** [NamelessMC/Nameless#490]
Hello, how do I do so at my appearing last 5 contribution but the last 10 contribution

**Comment by samerton** [comment]
Are you referring to [these posts](http://i.imgur.com/mp2O49A.jpg) on profile pages?

**Comment by zikycz** [comment]
I mean this: https://ctrlv.cz/2KwW

**Comment by samerton** [comment]
In order to change the latest posts so there are 10 displayed instead of 5, you can simply change [line 433](https://github.com/NamelessMC/Nameless/blob/master/pages/forum/index.php#L433) of **pages/forum/index.php** and [line 813](https://github.com/NamelessMC/Nameless/blob/master/pages/forum/view_forum.php#L813) of **pages/forum/view_forum.php**, changing the 5 to 10.

**Comment by zikycz** [comment]
Tanks

**Comment by baxandrei** [comment]
In like this suggestion, and some users don't know how edit scripts.. this future option îs a good addon.

**Comment by Derkades** [comment]
@samerton Is this already a thing in v2?

**Comment by samerton** [comment]
@Derkades Not at the moment, it's still something I'm hoping to add in the future though.

**Comment by zikycz** [comment]
I've already fixed this bug in Chrome. Thank you

**Comment by samerton** [comment]
Combining with #1123
