### ISSUE TITLE
[SUGESSTION] Option to hide the root user and rename/remove the admin group.

### ISSUE THREAD

**Issue by dangerBEclose** [NamelessMC/Nameless#505]
Pretty much my title :-P
Option to hide the root user and rename/remove the admin group would be good.
Also a way to set a custom immage as background, but keep the forums and other things like social, teamspeak, members, etc. its background like the selected theme.
So i mean having a custom immage but keep all readable since the bacbground of all text stays like it is (by the selected theme)
Sorry if you dont understand it, my main language ins't English.

**Comment by MuhsinunCool** [comment]
+1 Yea I need this too. I just ended up making a COMPLETELY separate account and creating another group with afmin permissions called Owner and put my new account in that group

**Comment by samerton** [comment]
It's already possible to rename the Admin group (if you want to create an Owner group for the root account, simply renaming the Admin group is the best way to do this), however due to a few people accidentally deleting the admin group and locking themselves out of the AdminCP, the ability to delete the group won't be re-added.

It's possible to upload a custom background image in the version 2 pre-releases.

**Comment by DoraKlikOpDora** [comment]
@samerton I don't think that this is a big problem, because it is possible to change it in the database.

But do I break stuff when I give my admin group another ID than it is now, or will things get strange..?

**Comment by samerton** [comment]
@DoraKlikOpDora Unfortunately not everyone knows how to modify their database, and in order to cater to all users I feel like it's best to keep these options disabled. In older releases, when the options were enabled, there were a large number of reports of users accidentally deleting their admin group without knowing how to get it back.

As for changing the group ID, if I remember correctly there are parts of the software which rely on the admin group ID being 2, so it's best this isn't changed.

**Comment by samerton** [comment]
I'll close this issue:

- it's possible to upload a custom background in v2
- it's possible to fully customise the HTML/CSS for the site with the v2 template system
- it's not possible to delete the default admin group, however you can rename it and re-order groups in v2
