### ISSUE TITLE
[SUGGESTION] Dubtrack integration

### ISSUE THREAD

**Issue by dangerBEclose** [NamelessMC/Nameless#507]
Can you implement Dubtrack integration?

**Comment by samerton** [comment]
I'll see what I can do, are there any features in particular you'd like to see?

**Comment by dangerORclose** [comment]
Yes, I have a lot of ideas,  but I don't want go go and spam this full with them. 
But one of them is the option to set who is allowed to set a specified flag. (on the forums). 
Since it's useful like n a server idea's or players report forum to mark them as accepted or not. But it's bad if the user can just set the flag to what they want.

**Comment by samerton** [comment]
Dubtrack no longer seems to be operational
