### ISSUE TITLE
[BUG] NASCAR TRANSELATION

### ISSUE THREAD

**Issue by dangerORclose** [NamelessMC/Nameless#508]
The navbar links like home, ban appeal, etc.  stay at English when you change the language to Dutch.

**Comment by DoraKlikOpDora** [comment]
I have updated the Dutch language and fixed some things.
Although, the words home, navbar and some other things are still in English. I don't think most Dutch people like it when literally every word is Dutch. It is rare when you see a Dutch page saying instead of "Home" the word "Thuis" or "Voorpagina". If you do not like it that way, feel free to edit it yourself in the file: /styles/language/Dutch/language.php. You will be able to change every word on your website.

Updated Dutch translation: https://github.com/NamelessMC/Nameless/pull/511

**Comment by samerton** [comment]
Is this fixed by #511?

**Comment by samerton** [comment]
I'll mark this issue as closed.
