### ISSUE TITLE
Fatal error: Class 'Input' not found

### ISSUE THREAD

**Issue by DirectGamerHD** [NamelessMC/Nameless#60]
Fatal error: Class 'Input' not found in /home/{redacted}/public_html/infamous/install.php on line 664

My first problem was solved when I moved "install.php" from "pages" to the root directory. Not sure what the issue is. I have a DB up and ready, but the install page still isn't working.

**Comment by samerton** [comment]
The install.php file will need to remain within the pages directory in order to function correctly.

If the previous issue you were experiencing was related to a 404 not found error, you'll need to follow [these steps](http://askubuntu.com/a/48363) to fix that error; all other pages will experience the 404 error without carrying out this fix.

**Comment by samerton** [comment]
I'm going to go ahead and close this as it's down to the server configuration, and the steps in the previous comment will fix this issue.
