### ISSUE TITLE
Visual Vote Glitch

### ISSUE THREAD

**Issue by SuperRonanCraft** [NamelessMC/Nameless#703]
Bug.
Release 1.0.16.
Vote page glitches after you add more than 4 sites.
Screenshot: http://i.imgur.com/y0ChHB7.png
Maybe is wasn't though out after a certain amount of links?

**Comment by samerton** [comment]
Thanks for the report, it's hopefully fixed in 0478bbd68159ddb8d93ed821922d7bd1090fbe84, to apply the fix now you can edit **pages/vote.php** in a text editor, delete everything inside, and replace it with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/0478bbd68159ddb8d93ed821922d7bd1090fbe84/pages/vote.php).
