### ISSUE TITLE
Email subscriptions for news or specific forums

### ISSUE THREAD

**Issue by Norge100** [NamelessMC/Nameless#726]
On V2: subscribe as email

When we got an email:
Moderator or Admin can send all pepole who enable subscribe (can disable as UserCP)
When new news has added
When pepole selected subscribe on forum

I think that's a good idea?

**Comment by Derkades** [comment]
It should be notifications only by default, and an option to turn on email notifications for forum posts in user settings.

**Comment by redbau** [comment]
@samerton can we do anything to help make this a priority for V2 launch? Seems exponentially useful and like something both users and server owners will love. Please consider increasing the priority of this. 🥇 🙌

**Comment by redbau** [comment]
Email notifications is my #1 feature request for 2.0 — my players and staff ❤️ this request.

With notifications many threads and replies that remain unanswered would be lively and quickly followed-up with. Every forum and social media platform does this already because it's incredibly powerful for user retention.

@samerton this strikes me as straightforward since Nameless is already sending login/password emails, is there something that makes this non-trivial for implementation? This feature request is almost 2 years old, just wondering what the plan is here.

**Comment by samerton** [comment]
Promoted to the v2 project board, it'll be in the full v2 release :)

**Comment by Aberdeener** [comment]
Just started this today. Should be done within 24 hours or so!

**Comment by Aberdeener** [comment]
#1701 adds this in!
@Derkades can you close this?
