### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by Root3287** [NamelessMC/Nameless#745]
Discussion/Question
Every version that has multiple languages
Different countries have different rules https://youtu.be/0j74jcxSunY
Nope
Nature of language

**Comment by Derkades** [comment]
And in that video Tom also explains why software generally is in English only or does not support languages very different from English. Dealing with this is a pain in the ass. 

I am not sure why you linked that video as a reason for @samerton to implement this, since I think the main point of the video is to highlight the complexity in program internationalisation.

**Comment by samerton** [comment]
At the moment there are no known situations where the current translation system isn't sufficient (in v2 anyway).

**Comment by Derkades** [comment]
As explained in the video, the current translation system is insufficient for some languages with special rules different from English, for example in some languages part of or an entire phrase might be different if just one word changes, so just replacing {x} will not work.

**Comment by samerton** [comment]
When these issues are found the terms can be updated to resolve them, however with our current translations there aren't any problems. As I can't really plan ahead for this, I'll mark this issue as closed.
