### ISSUE TITLE
Help with a theme

### ISSUE THREAD

**Issue by MexmexMe** [NamelessMC/Nameless#874]
Hey,

i want to install this style: https://www.spigotmc.org/resources/nextyle-namelessmc-theme.38514/
I dont understand how to install.
Can you help me, please?

Thanks

**Comment by samerton** [comment]
Hi,

Firstly you need to be using NamelessMC version 2 (which is still in pre-release stages).
Then, you can install the updated template from [this GitHub repo](https://github.com/samerton/Nameless-Nextyle-Updated) instead of the Spigot resource, and installation instructions can be found in the readme.

**Comment by MexmexMe** [comment]
I have installed Nameless already.
Can I install the theme afterwards?

**Comment by samerton** [comment]
Absolutely, just follow the steps in my previous reply :)

**Comment by MexmexMe** [comment]
Okay, thanks.
Now I have installed the module but the style is not displayed.
At "Styles" when I scan for new Styles, there isnt the Style.

**Comment by samerton** [comment]
Have you previously deleted any templates?

**Comment by MexmexMe** [comment]
No, I havent deleted any templates.

**Comment by samerton** [comment]
If you enable debugging in the AdminCP -> Core -> Debugging and Maintenance tab, are there any errors appearing on the styles page?

**Comment by samerton** [comment]
Were you able to resolve this issue @MexmexMe?

**Comment by samerton** [comment]
I'll mark this issue as closed, if you're still experiencing the issue please feel free to re-open.
