### ISSUE TITLE
Problem with tags

### ISSUE THREAD

**Issue by iTheEnder** [NamelessMC/Nameless#935]
Hello

On my site, I created two forums: one for discussion and the other for category, when creating labels, this appears:
<a href='https://imgur.com/a/mZ263'>click me xD</a>

in the forum tags section, I do not see anything, I think the forums that I created should appear.

When creating a post in any of the 2 forums, this appears

<a href="https://imgur.com/h1VQUxC">click again xd</a>

As you can see, in the tags section, the default tag "Nada" appears (because my language is Spanish) and at least I think that the tags I created should appear there

I am using the latest version of NamelessMC. Sorry if the doubt is something obvious, but I could not solve it

**Comment by samerton** [comment]
Hi,

The first thing is to create a category for your forums. To do this, you simply create a new forum, and check the box to set it as a "Category" instead of a "Discussion Forum".

Then, edit your existing discussion forums, and set their "Parent Forum" option to this new category. An example of a category is the "NamelessMC" section on the [official website](https://namelessmc.com/forum), and "News & Announcements" and "General Discussion" are discussion forums.

Once that is done, the box underneath "Etiqueta de Foros" will have forums in it, which you need to select for the label to appear in that forum.

Hope that helps.

**Comment by iTheEnder** [comment]
Hello, and thanks for the help, if it worked for me. Thank you very much.

**Comment by samerton** [comment]
No problem! :)
