### ISSUE TITLE
Mass message to all members

### ISSUE THREAD

**Issue by ItsVinnyX** [NamelessMC/Nameless#949]
Suggestion for all versions
Add a mass message option to all members.

**Comment by Derkades** [comment]
For now you can add news on the homepage and announcements at the top of every page

**Comment by PixelNotFound** [comment]
or for specific ranks?

**Comment by DSArtyFixLife** [comment]
@PixelNotFound it is possible, if you will using php check if user has required group and display message. Else you only need to wait, when will they add this feature.

**Comment by samerton** [comment]
If you mass message all users:
- Should individual private messages be sent to every single user on the site, each one just between you and the other user, or...
- Should there be one private message created with all users added?

**Comment by RichardB122** [comment]
@samerton I think it would be best for there to be a separate conversation for each user, otherwise it could end up becoming a mass group conversation and quickly get out of control with replies.

Also it might be best for the user to be a faked system user so that the admin doesn't end up having millions of conversations with everyone on the site.

**Comment by samerton** [comment]
I'm currently thinking of something like this:
- A new private message is created per user
- By default, it is hidden to the sender
- If another user replies to the message, it then becomes visible to the sender

**Comment by Aberdeener** [comment]
Added mass email function yesterday, thanks

**Comment by Derkades** [comment]
@Aberdeener Does your mass message function only send enails, or also website announcements/notifications/alerts?
