### ISSUE TITLE
Update from 1.0.19 to V2 PR3

### ISSUE THREAD

**Issue by bloopkins** [NamelessMC/Nameless#969]
### Template:
* What kind of issue is it (Question, Bug, etc.)? Question
* In which version of NamelessMC did it occur (1.x.x)? 1.0.19
* How would you describe the issue? How do you upgrade to v2 PR3?

I would like to update my site from 1.0.19 to PR3 but cannot figure out how to do that. is there a way to?

**Comment by samerton** [comment]
Hi,

First, back up your v1 files and the database. It is not possible to downgrade from version 2 back to version 1 afterwards.

Next, delete all version 1 files from your website, but **don't** touch the database. You can then upload the version 2 files (I'd recommend getting the latest files from [here](https://github.com/NamelessMC/Nameless/archive/v2.zip) instead of the pre-release, as there are several new features/fixed bugs).

Finally, you can run through the installer, telling it you want to upgrade from version 1. You will then be asked for your database details for the version 1 installation.

**Comment by samerton** [comment]
I'll mark this as closed, if you have any further questions please feel free to re-open.
